### ISSUE TITLE
コンセプトアート

### ISSUE THREAD

**Issue by noir-neo** [noir-neo/mad-explosion-race-game#1]

**Comment by shelf703** [comment]
![1p](https://user-images.githubusercontent.com/13808378/39396506-64e7230e-4b2a-11e8-8fa1-35db9f2d00b7.png)

**Comment by shelf703** [comment]
![1p2p](https://user-images.githubusercontent.com/13808378/39396511-756f2cf8-4b2a-11e8-9561-6018fb124a02.png)
