### ISSUE TITLE
設計

### ISSUE THREAD

**Issue by noir-neo** [noir-neo/mad-explosion-race-game#2]

**Comment by maku693** [comment]
![default](https://user-images.githubusercontent.com/22081383/39397393-7eeeb88e-4b39-11e8-8b31-7ce0d55a2a2f.jpg)

**Comment by maku693** [comment]
![2](https://user-images.githubusercontent.com/22081383/39397428-e954d636-4b39-11e8-807b-2313eea8178b.jpg)
